name: Build and Deploy to dist

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout el código fuente
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Configurar Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'

    # 3. Instalar dependencias
    - name: Install dependencies
      run: npm i

    # 4. Construir la aplicación
    - name: Build application
      run: npm run build

    # 5. Desplegar a la rama `dist`
    - name: Deploy to dist branch
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git checkout --orphan dist
        git --work-tree dist add --all
        git --work-tree dist commit -m "Deploy to dist branch"
        git push origin HEAD:dist --force

    # 6. Configurar SSH
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # 7. Sincronizar con el servidor
    - name: Deploy to server
      run: |
        ssh-keyscan -H 172.18.79.133 >> ~/.ssh/known_hosts
        rsync -avz ./dist/ erikh@172.18.79.133:/home/erikh/projects/store-app-container/store-app/